name: health_care_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  badges: ^3.0.2
  google_fonts: ^6.3.1
  dio: ^5.9.0
  provider: ^6.1.5+1
  easy_date_timeline: ^2.0.9
  smooth_page_indicator: ^1.2.1
  emoji_picker_flutter: ^4.3.0
  file_picker: ^10.3.3
  image_picker: ^1.2.0
  record: ^6.1.1
  carousel_slider: ^5.1.1 
  animated_bottom_navigation_bar: ^1.4.0
  uuid: ^4.5.2

 
 # firebase packages
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.2
  modal_progress_hud_nsn: ^0.5.1
# <<<<<<< home-logic-signup-edit
  cached_network_image: ^3.3.1
  firebase_storage: 13.0.3
  open_file: ^3.5.10
  flutter_sound: ^9.28.0
  video_player: ^2.10.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0



flutter:
  uses-material-design: true
  assets:
    - lib/images/
    - lib/images/icons/
    - lib/images/DoctorSpecialist/ 
    - lib/images/Doctors/
